import { GoogleGenAI, Type } from "@google/genai";
import { sanitizeSpanishWord } from "../generators/wordSearch";

export interface GenerateActivitiesOptions {
  text: string;
  level?: string;
  language?: string;
}

export interface GeneratedVocabularyItem {
  word: string;
  clue: string;
}

export interface GeneratedCryptogram {
  phrase: string;
  hint: string;
}

export interface GeneratedActivitiesResult {
  themeTitle: string;
  summary: string;
  vocabulary: GeneratedVocabularyItem[];
  clozeParagraph: string;
  cryptogram: GeneratedCryptogram;
}

export const activitiesResponseSchema = {
  type: Type.OBJECT,
  description: "Educational activity pack structure with vocabulary, cloze text, and cryptogram",
  properties: {
    themeTitle: {
      type: Type.STRING,
      description: "Concise title for the educational topic (max 60 chars)",
    },
    summary: {
      type: Type.STRING,
      description: "Short pedagogical overview of the topic (2-3 sentences)",
    },
    vocabulary: {
      type: Type.ARRAY,
      description: "List of 12 to 20 key vocabulary words with pedagogical clues",
      items: {
        type: Type.OBJECT,
        properties: {
          word: {
            type: Type.STRING,
            description: "Single uppercase word without accents, 3-15 letters (e.g. FOTOSINTESIS, CELULA)",
          },
          clue: {
            type: Type.STRING,
            description: "Concise pedagogical definition or clue, max 120 chars, not containing the word itself",
          },
        },
        required: ["word", "clue"],
      },
    },
    clozeParagraph: {
      type: Type.STRING,
      description: "Pedagogical paragraph of 50-100 words with 4-8 key words inside brackets like [palabra]",
    },
    cryptogram: {
      type: Type.OBJECT,
      description: "A memorable key takeaway sentence in uppercase with a clue",
      properties: {
        phrase: {
          type: Type.STRING,
          description: "Memorable takeaway phrase or sentence, 20-80 characters, uppercase",
        },
        hint: {
          type: Type.STRING,
          description: "Helpful pedagogical hint guiding the student",
        },
      },
      required: ["phrase", "hint"],
    },
  },
  required: [
    "themeTitle",
    "summary",
    "vocabulary",
    "clozeParagraph",
    "cryptogram",
  ],
};

/**
 * Sanitizes and validates the structured output generated by Gemini.
 */
export function sanitizeGeneratedActivities(raw: unknown): GeneratedActivitiesResult {
  if (!raw || typeof raw !== "object") {
    throw new Error("Formato de respuesta inválido.");
  }

  const data = raw as Record<string, unknown>;

  const themeTitle =
    typeof data.themeTitle === "string" && data.themeTitle.trim()
      ? data.themeTitle.trim().slice(0, 100)
      : "Actividades Temáticas";

  const summary = typeof data.summary === "string" ? data.summary.trim() : "";

  // Sanitize vocabulary: clean Spanish uppercase words, deduplicate
  const rawVocab = Array.isArray(data.vocabulary) ? data.vocabulary : [];
  const seen = new Set<string>();
  const vocabulary: GeneratedVocabularyItem[] = [];

  for (const item of rawVocab) {
    if (!item || typeof item !== "object") continue;
    const entry = item as Record<string, unknown>;
    const rawWord = typeof entry.word === "string" ? entry.word : "";
    const cleanWord = sanitizeSpanishWord(rawWord);
    const clue = typeof entry.clue === "string" ? entry.clue.trim().slice(0, 150) : "";

    if (cleanWord.length >= 3 && cleanWord.length <= 15 && !seen.has(cleanWord)) {
      seen.add(cleanWord);
      vocabulary.push({
        word: cleanWord,
        clue,
      });
    }
  }

  if (vocabulary.length < 3) {
    throw new Error("Gemini no generó suficiente vocabulario válido (mínimo 3 palabras).");
  }

  // Sanitize cloze paragraph
  let clozeParagraph = typeof data.clozeParagraph === "string" ? data.clozeParagraph.trim() : "";
  if (!clozeParagraph) {
    const sampleWords = vocabulary.slice(0, 4).map((v) => `[${v.word}]`).join(", ");
    clozeParagraph = `En esta lección sobre ${themeTitle}, estudiamos conceptos fundamentales como ${sampleWords}.`;
  }

  // Sanitize cryptogram
  const rawCrypto =
    typeof data.cryptogram === "object" && data.cryptogram !== null
      ? (data.cryptogram as Record<string, unknown>)
      : {};

  let phrase = typeof rawCrypto.phrase === "string" ? rawCrypto.phrase.trim().toUpperCase() : "";
  let hint = typeof rawCrypto.hint === "string" ? rawCrypto.hint.trim().slice(0, 150) : "";

  if (phrase.length < 10) {
    const keyWords = vocabulary.slice(0, 3).map((v) => v.word).join(" ");
    phrase = `${themeTitle.toUpperCase()}: ${keyWords}`;
    hint = hint || `Concepto clave sobre ${themeTitle}`;
  }

  phrase = phrase.slice(0, 80);

  return {
    themeTitle,
    summary,
    vocabulary: vocabulary.slice(0, 20),
    clozeParagraph,
    cryptogram: {
      phrase,
      hint: hint || `Pista: ${themeTitle}`,
    },
  };
}

/**
 * Generates an activity pack from input text using Google Gemini (gemini-2.5-flash).
 */
export async function generateActivitiesFromText({
  text,
  level = "primaria",
  language = "español",
}: GenerateActivitiesOptions): Promise<GeneratedActivitiesResult> {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    throw new Error("La API de Gemini no está configurada (GEMINI_API_KEY requerida).");
  }

  const trimmedText = text.trim();
  if (trimmedText.length < 30) {
    throw new Error("El texto debe tener al menos 30 caracteres.");
  }
  if (trimmedText.length > 30000) {
    throw new Error("El texto no puede superar los 30.000 caracteres.");
  }

  const ai = new GoogleGenAI({ apiKey });

  const systemInstruction = `Eres un docente experto y pedagogo de habla hispana especializado en diseño de material didáctico imprimible.
Analiza el texto pedagógico, resumen o apunte escolar provisto por el usuario y genera una estructura didáctica completa y coherente en formato JSON.

Reglas obligatorias:
1. "themeTitle": Título conciso, educativo y atractivo (máximo 60 caracteres).
2. "summary": Resumen breve de 2-3 oraciones que sintetice la idea central para el nivel indicado.
3. "vocabulary":
   - Extrae entre 12 y 20 palabras clave indispensables.
   - Cada "word" debe ser UNA SOLA PALABRA en mayúsculas, de 3 a 15 letras, limpia (solo letras A-Z y Ñ, sin espacios, sin tildes ni guiones).
   - Cada "clue" debe ser una definición clara y breve (máximo 120 caracteres) adecuada para el nivel escolar (${level}). NUNCA menciones la propia palabra ni su raíz dentro de la pista.
4. "clozeParagraph":
   - Un texto pedagógico coherente de 50 a 100 palabras que explique el tema para estudiantes de nivel ${level}.
   - Debe tener entre 4 y 8 palabras clave encerradas entre corchetes, por ejemplo: "El [Sol] es el centro de nuestro [sistema] solar."
   - Las palabras entre corchetes deben ser palabras relevantes (preferentemente del vocabulario clave).
5. "cryptogram":
   - "phrase": Una frase o enseñanza principal memorable del tema de 20 a 80 caracteres en MAYÚSCULAS (puede incluir espacios y signos de puntuación).
   - "hint": Una pista didáctica y orientadora (máximo 120 caracteres) para resolverla.

Idioma: ${language}.
Nivel educativo: ${level}.`;

  const userPrompt = `A continuación se encuentra el texto de la lección escolar para generar las actividades:

---
${trimmedText}
---

Genera el JSON estructurado respetando estrictamente el esquema indicado.`;

  const response = await ai.models.generateContent({
    model: "gemini-2.5-flash",
    contents: userPrompt,
    config: {
      systemInstruction,
      responseMimeType: "application/json",
      responseSchema: activitiesResponseSchema,
    },
  });

  const rawJson = response.text;
  if (!rawJson) {
    throw new Error("Gemini no devolvió ninguna respuesta de texto.");
  }

  let parsed: unknown;
  try {
    parsed = JSON.parse(rawJson);
  } catch (parseErr) {
    console.error("Error parsing JSON from Gemini:", parseErr, rawJson);
    throw new Error("No se pudo interpretar la respuesta generada por Gemini.");
  }

  return sanitizeGeneratedActivities(parsed);
}
