import { sanitizeSpanishWord } from "../generators/wordSearch";

export interface GenerateActivitiesOptions {
  text?: string;
  pdfBase64?: string;
  level?: string;
  language?: string;
}

export interface GeneratedVocabularyItem {
  word: string;
  clue: string;
}

export interface GeneratedCryptogram {
  phrase: string;
  hint: string;
}

export interface GeneratedActivitiesResult {
  themeTitle: string;
  summary: string;
  vocabulary: GeneratedVocabularyItem[];
  clozeParagraph: string;
  cryptogram: GeneratedCryptogram;
}

export class GeminiApiError extends Error {
  status: number;
  constructor(message: string, status: number) {
    super(message);
    this.name = "GeminiApiError";
    this.status = status;
  }
}

export const activitiesResponseSchema = {
  type: "OBJECT",
  description: "Educational activity pack structure with vocabulary, cloze text, and cryptogram",
  properties: {
    themeTitle: {
      type: "STRING",
      description: "Concise title for the educational topic (max 60 chars)",
    },
    summary: {
      type: "STRING",
      description: "Short pedagogical overview of the topic (2-3 sentences)",
    },
    vocabulary: {
      type: "ARRAY",
      description: "List of 12 to 20 key vocabulary words with pedagogical clues",
      items: {
        type: "OBJECT",
        properties: {
          word: {
            type: "STRING",
            description: "Single uppercase word without accents, 3-15 letters (e.g. FOTOSINTESIS, CELULA)",
          },
          clue: {
            type: "STRING",
            description: "Concise pedagogical definition or clue, max 120 chars, not containing the word itself",
          },
        },
        required: ["word", "clue"],
      },
    },
    clozeParagraph: {
      type: "STRING",
      description: "Pedagogical paragraph of 50-100 words with 4-8 key words inside brackets like [palabra]",
    },
    cryptogram: {
      type: "OBJECT",
      description: "A memorable key takeaway sentence in uppercase with a clue",
      properties: {
        phrase: {
          type: "STRING",
          description: "Memorable takeaway phrase or sentence, 20-80 characters, uppercase",
        },
        hint: {
          type: "STRING",
          description: "Helpful pedagogical hint guiding the student",
        },
      },
      required: ["phrase", "hint"],
    },
  },
  required: [
    "themeTitle",
    "summary",
    "vocabulary",
    "clozeParagraph",
    "cryptogram",
  ],
};

/**
 * Sanitizes and validates the structured output generated by Gemini.
 */
export function sanitizeGeneratedActivities(raw: unknown): GeneratedActivitiesResult {
  if (!raw || typeof raw !== "object") {
    throw new Error("Formato de respuesta inválido.");
  }

  const data = raw as Record<string, unknown>;

  const themeTitle =
    typeof data.themeTitle === "string" && data.themeTitle.trim()
      ? data.themeTitle.trim().slice(0, 100)
      : "Actividades Temáticas";

  const summary =
    typeof data.summary === "string" && data.summary.trim()
      ? data.summary.trim()
      : `Actividades sobre ${themeTitle}`;

  // Process and sanitize vocabulary items
  const rawVocab = Array.isArray(data.vocabulary) ? data.vocabulary : [];
  const seenWords = new Set<string>();
  const vocabulary: GeneratedVocabularyItem[] = [];

  for (const item of rawVocab) {
    if (!item || typeof item !== "object") continue;
    const rawWord = (item as Record<string, unknown>).word;
    const rawClue = (item as Record<string, unknown>).clue;

    if (typeof rawWord !== "string") continue;
    const cleanWord = sanitizeSpanishWord(rawWord);

    // Enforce reasonable length and uniqueness (3 to 18 chars)
    if (cleanWord.length < 3 || cleanWord.length > 18 || seenWords.has(cleanWord)) {
      continue;
    }

    seenWords.add(cleanWord);
    const cleanClue =
      typeof rawClue === "string" && rawClue.trim()
        ? rawClue.trim().slice(0, 180)
        : `Concepto relacionado con ${themeTitle}`;

    vocabulary.push({
      word: cleanWord,
      clue: cleanClue,
    });
  }

  if (vocabulary.length < 3) {
    throw new Error("Gemini no generó suficiente vocabulario válido (mínimo 3 palabras).");
  }

  // Ensure cloze paragraph is usable
  let clozeParagraph =
    typeof data.clozeParagraph === "string" && data.clozeParagraph.trim()
      ? data.clozeParagraph.trim()
      : "";

  if (!clozeParagraph) {
    const sampleWords = vocabulary.slice(0, 4).map((v) => `[${v.word}]`);
    clozeParagraph = `En esta lección sobre ${themeTitle}, estudiamos conceptos como ${sampleWords.join(", ")}.`;
  }

  // Process cryptogram
  const rawCrypto =
    data.cryptogram && typeof data.cryptogram === "object"
      ? (data.cryptogram as Record<string, unknown>)
      : {};

  let cryptoPhrase =
    typeof rawCrypto.phrase === "string" && rawCrypto.phrase.trim()
      ? rawCrypto.phrase.trim().toUpperCase()
      : "";

  if (!cryptoPhrase || cryptoPhrase.length < 8) {
    cryptoPhrase =
      vocabulary.length > 0
        ? `EL ESTUDIO DE ${themeTitle.toUpperCase()} ES FUNDAMENTAL`
        : "APRENDER CADA DIA ES UN GRAN LOGRO";
  }

  const cryptoHint =
    typeof rawCrypto.hint === "string" && rawCrypto.hint.trim()
      ? rawCrypto.hint.trim()
      : `Pista sobre ${themeTitle}`;

  return {
    themeTitle,
    summary,
    vocabulary,
    clozeParagraph,
    cryptogram: {
      phrase: cryptoPhrase,
      hint: cryptoHint,
    },
  };
}

export async function getSupportedModels(apiKey: string): Promise<string[]> {
  try {
    const listUrl = `https://generativelanguage.googleapis.com/v1beta/models?key=${encodeURIComponent(apiKey)}`;
    const res = await fetch(listUrl);
    if (res.ok) {
      const data = await res.json();
      const models = Array.isArray(data.models) ? data.models : [];
      return models
        .filter((m: { supportedGenerationMethods?: string[] }) =>
          Array.isArray(m.supportedGenerationMethods) &&
          m.supportedGenerationMethods.includes("generateContent")
        )
        .map((m: { name: string }) => m.name.replace(/^models\//, ""));
    }
  } catch (err) {
    console.warn("Could not fetch models list from Gemini API:", err);
  }
  return [];
}

export async function resolveGeminiModel(apiKey: string): Promise<string[]> {
  const preferred = [
    "gemini-3.8-flash",
    "gemini-3.5-flash",
    "gemini-3.5-flash-lite",
    "gemini-2.5-flash",
    "gemini-2.0-flash",
  ];

  const available = await getSupportedModels(apiKey);
  if (available.length > 0) {
    const matched = preferred.filter((p) => available.includes(p));
    if (matched.length > 0) {
      return matched;
    }
    const flashModels = available.filter((m) => m.includes("flash") && !m.includes("exp"));
    if (flashModels.length > 0) {
      return flashModels;
    }
    return available;
  }

  return preferred;
}

/**
 * Calls Google Gemini REST API directly using native fetch.
 * Generates vocabulary, cloze text, and cryptogram from text in a single roundtrip.
 */
export async function generateActivitiesFromText({
  text = "",
  pdfBase64,
  level = "primaria",
  language = "español",
}: GenerateActivitiesOptions): Promise<GeneratedActivitiesResult> {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    throw new Error("La API de Gemini no está configurada (GEMINI_API_KEY requerida).");
  }

  const cleanPdfBase64 = pdfBase64
    ? pdfBase64.replace(/^data:application\/pdf;base64,/, "").trim()
    : undefined;

  const trimmedText = (text || "").trim();

  if (trimmedText.length < 30 && !cleanPdfBase64) {
    throw new Error("Debes ingresar al menos 30 caracteres de texto o adjuntar un archivo PDF.");
  }
  if (trimmedText.length > 30000) {
    throw new Error("El texto no puede superar los 30.000 caracteres.");
  }

  const systemInstruction = `Eres un docente experto y pedagogo de habla hispana especializado en diseño de material didáctico imprimible.
Analiza el material pedagógico, resumen, apunte escolar o documento PDF adjunto provisto por el usuario y genera una estructura didáctica completa y coherente en formato JSON.

Reglas obligatorias:
1. "themeTitle": Título conciso, educativo y atractivo (máximo 60 caracteres).
2. "summary": Resumen breve de 2-3 oraciones que sintetice la idea central para el nivel indicado.
3. "vocabulary":
   - Extrae entre 12 y 20 palabras clave indispensables.
   - Cada "word" debe ser UNA SOLA PALABRA en mayúsculas, de 3 a 15 letras, limpia (solo letras A-Z y Ñ, sin espacios, sin tildes ni guiones).
   - Cada "clue" debe ser una definición clara y breve (máximo 120 caracteres) adecuada para el nivel escolar (${level}). NUNCA menciones la propia palabra ni su raíz dentro de la pista.
4. "clozeParagraph":
   - Un texto pedagógico coherente de 50 a 100 palabras que explique el tema para estudiantes de nivel ${level}.
   - Debe tener entre 4 y 8 palabras clave encerradas entre corchetes, por ejemplo: "El [Sol] es el centro de nuestro [sistema] solar."
   - Las palabras entre corchetes deben ser palabras relevantes (preferentemente del vocabulario clave).
5. "cryptogram":
   - "phrase": Una frase o enseñanza principal memorable del tema de 20 a 80 caracteres en MAYÚSCULAS (puede incluir espacios y signos de puntuación).
   - "hint": Una pista didáctica y orientadora (máximo 120 caracteres) para resolverla.

Idioma: ${language}.
Nivel educativo: ${level}.`;

  let userPrompt: string;
  if (cleanPdfBase64) {
    if (trimmedText) {
      userPrompt = `Se ha adjuntado un documento PDF con material pedagógico (apuntes, diapositivas, páginas escaneadas o figuras). Analiza exhaustivamente el contenido del archivo PDF y complementa con las siguientes notas o instrucciones del usuario:

---
${trimmedText}
---

Extrae los conceptos educativos principales y genera el JSON estructurado respetando estrictamente el esquema indicado.`;
    } else {
      userPrompt = `Se ha adjuntado un documento PDF con material pedagógico (apuntes, diapositivas, páginas escaneadas o figuras). Analiza exhaustivamente el contenido del archivo PDF para extraer los conceptos educativos clave y generar el JSON estructurado respetando estrictamente el esquema indicado.`;
    }
  } else {
    userPrompt = `A continuación se encuentra el texto de la lección escolar para generar las actividades:

---
${trimmedText}
---

Genera el JSON estructurado respetando estrictamente el esquema indicado.`;
  }

  const parts: Array<{ text?: string; inline_data?: { mime_type: string; data: string } }> = [
    { text: userPrompt },
  ];
  if (cleanPdfBase64) {
    parts.push({
      inline_data: {
        mime_type: "application/pdf",
        data: cleanPdfBase64,
      },
    });
  }

  const candidateModels = await resolveGeminiModel(apiKey);
  let lastError: Error | null = null;

  for (const model of candidateModels) {
    const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${encodeURIComponent(apiKey)}`;

    try {
      const response = await fetch(endpoint, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          systemInstruction: {
            parts: [{ text: systemInstruction }],
          },
          contents: [
            {
              role: "user",
              parts,
            },
          ],
          generationConfig: {
            responseMimeType: "application/json",
            responseSchema: activitiesResponseSchema,
          },
        }),
      });

      if (!response.ok) {
        const errorData = await response.json().catch(() => null);
        const errorMsg = errorData?.error?.message || `HTTP ${response.status} ${response.statusText}`;
        console.error(`Gemini API error with model ${model}:`, response.status, errorMsg);

        // If model not found (404) or temporarily unavailable (503), try next model
        if ((response.status === 404 || response.status === 503) && model !== candidateModels[candidateModels.length - 1]) {
          lastError = new GeminiApiError(`${model}: ${errorMsg}`, response.status);
          continue;
        }

        throw new GeminiApiError(errorMsg, response.status);
      }

      const data = await response.json();
      const rawJson = data?.candidates?.[0]?.content?.parts?.[0]?.text;
      if (!rawJson) {
        throw new Error(`Gemini (${model}) no devolvió ninguna respuesta de texto.`);
      }

      let parsed: unknown;
      try {
        parsed = JSON.parse(rawJson);
      } catch (parseErr) {
        console.error("Error parsing JSON from Gemini:", parseErr, rawJson);
        throw new Error("No se pudo interpretar la respuesta generada por Gemini.");
      }

      return sanitizeGeneratedActivities(parsed);
    } catch (err) {
      if (err instanceof GeminiApiError && (err.status === 404 || err.status === 503)) {
        lastError = err;
        continue;
      }
      throw err;
    }
  }

  throw lastError || new Error("No se pudo conectar con los modelos de Gemini.");
}
